### ISSUE TITLE
The Problem about README

### ISSUE THREAD

**Issue by zhyuchen** [cuhk-eda/dr-cu#2] opened 2019-09-16 07:14 UTC
Thanks for sharing your open-source code. I have run the project in my machine and I find the result table of README is different from what I get. In the README, the score of ispd19_test5 is 3297338, but the score I get is 4374626.52. Because the short count and short area are different. In addition, the results of other testcases are slightly different from what I get.

**Comment by Rholais** [comment] 2019-09-17 04:16
I ran `ispd19_test5` again and the obtained score was still 3297338.
Could you try our released [binary](https://github.com/cuhk-eda/dr-cu/releases) and see if there is any difference?
If would also be helpful for us to diagnose if you could share your output DEF file here.

Slight differences in short area may be caused by non-deterministic Innovus design rule check with multiple threads.
I have updated the evaluation scripts with `setMultiCpuUsage` removed.

**Comment by zhyuchen** [comment] 2019-09-18 07:10
I can get the same short count as you by using Innovus. However, the score of ispd19_test5 is also different from your score by your evaluation scripts, even if using your released binary. The DEF file is attached. Please check my DEF file.
[ispd19_test5.zip](https://github.com/cuhk-eda/dr-cu/files/3624896/ispd19_test5.zip)

**Comment by Rholais** [comment] 2019-09-19 08:17
The DEF file is identical to ours.
Are you using the [evaluator](https://github.com/cuhk-eda/dr-cu/tree/master/ispd19eval) in the repository?
It would also be helpful for us to diagnose if you could share the log of evaluator here.

The difference may be caused by the different version of Innovus.
Currently, we have `v17.16-s058_1` installed on our server.

**Comment by zhyuchen** [comment] 2019-09-19 09:05
Yes, I used your evaluator. The log of the evaluator is attached. Please hlep me diagnose it. The version of our innovus is v18.11-s100_1. Sorry for any inconvenience caused.
[ispd19_test5_eval_file.zip](https://github.com/cuhk-eda/dr-cu/files/3630320/ispd19_test5_eval_file.zip)

**Comment by Rholais** [comment] 2019-09-20 07:24
The evaluator provided by the Contest organizers [only supports Innovus 16.2x and 17.1x](http://www.ispd.cc/contests/19/ISPD_2019_registration.docx).
Please try the same Innovus `v17.16-s058_1` as ours.
If you look into the geometry report, there are 781 shorts between blockages and pins, which have nothing to do with the router and should be ignored from the report.

**Comment by Rholais** [comment] 2019-09-26 08:26
@zhyuchen I will close the issue if there is no other problem regarding [README.md](https://github.com/cuhk-eda/dr-cu/blob/master/README.md).

**Comment by zhyuchen** [comment] 2019-09-26 08:59
Thanks for your answers. I can't use the new version Innovus for the time being. If there are any other questions, I'll ask you. Sorry for any inconvenience caused.

**Comment by zhyuchen** [comment] 2019-09-26 09:01
You can close this issue.

**Comment by Rholais** [comment] 2019-09-26 09:10
Thanks for the feedback.
Actually, your current Innovus version `v18.11-s100_1` is newer than the newest version that the evaluation script support.
I will close the issue.

**Closed as completed by Rholais** 2019-09-26 09:10 UTC
